### ISSUE TITLE
Remove spam from the game please

### ISSUE THREAD

**Issue by GeorgeKosrs** [Ferrariic/Bot-Detector-Core-Files#3]
Hi Ferrariic

Can you use your expertise to remove spam from the game? I am sure you can easily detect players with your algo who spam gold farming websites, trading and gambling scams etc

Your plugin can constantly  learn to always stay up to date with the best spam filters

The work you are doing is amazing

**Comment by Ferrariic** [comment]
Once we've released our final version for the plugin, we can look into reducing spam from the game :) I would consider it fair to say that they'd be 'bots' as well, in a sense.

**Comment by Glennmen** [comment]
Has this ever been added? Really annoying to see all these "casino" bots in GE.
